Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,8 +1,12 @@
-name: Context testing
+name: pull_request
 on: push
 
 env:
   MY_NAME: "My Global Name"
+
+concurrency: 
+  group: ${{ github.head_ref || github.run_id }}
+  cancel-in-progress: true
 
 jobs:
   dump_contexts:
@@ -67,5 +71,43 @@ jobs:
     runs-on: ubuntu-latest
     needs: job1_output
     steps:
-      - run: echo ${{needs.job1_output.outputs.output1}} ${{needs.job1_output.outputs.output2}}
+      - name: echo output
+        id: echo_output
+        run: |
+          echo ${{needs.job1_output.outputs.output1}} ${{needs.job1_output.outputs.output2}}
+      
+      - name: The job has failed
+        id: failed_step
+        if: ${{ failure() }}
+        run: |
+          echo "previous step failed"
+      
+      - name: The job has success
+        id: success_step
+        if: ${{ success() }}
+        run: |
+          echo "previous step success"
+          
+      - name: The job has cancel
+        id: cancel_step
+        if: ${{ cancelled() }}
+        run: |
+          echo "previous step canceled"
+          
+      - name: The job always run
+        id: always_step
+        if: ${{ always() }}
+        run: |
+          echo "previous step canceled"
+          
+      - name: force Failing step
+        id: force_failed
+        run: exit 1
+      
+      - name: The demo step has failed
+        id: force_failed_if
+        if: ${{ failure() && steps.force_failed.conclusion == 'failure' }}
+        run: |
+          echo "previous step failed with steps check"
+         
         
